crc32_test = executable(
  'crc32_test',
  sources: ['tests/crc32/test.c'],
  dependencies: gencrc_dep,
  install: false,
)
test(
  'crc32',
  crc32_test,
)
crc16_test = executable(
  'crc16_test',
  sources: ['tests/crc16/test.c'],
  dependencies: gencrc_dep,
  install: false,
)
test(
  'crc16',
  crc16_test,
)
crc8_test = executable(
  'crc8_test',
  sources: ['tests/crc8/test.c'],
  dependencies: gencrc_dep,
  install: false,
)
test(
  'crc8',
  crc8_test,
)
crc32_table_test = executable(
  'crc32_table_test',
  sources: ['tests/crc32/table_test.c'],
  dependencies: gencrc_dep,
  install: false,
)
test(
  'crc32_table',
  crc32_table_test,
)
crc16_table_test = executable(
  'crc16_table_test',
  sources: ['tests/crc16/table_test.c'],
  dependencies: gencrc_dep,
  install: false,
)
test(
  'crc16_table',
  crc16_table_test,
)
crc8_table_test = executable(
  'crc8_table_test',
  sources: ['tests/crc8/table_test.c'],
  dependencies: gencrc_dep,
  install: false,
)
test(
  'crc8_table',
  crc8_table_test,
)
